apiVersion: v1
kind: Service
metadata:
  name: code-agent-svc-{{JOB_ID}}
  labels:
    app: code-capsule
    job-id: "{{JOB_ID}}"
spec:
  selector:
    job-name: code-agent-job-{{JOB_ID}}
  ports:
  - name: novnc
    port: 6080
    targetPort: 6080
    nodePort: {{NOVNC_NODEPORT}}
  - name: jupyter
    port: 8888
    targetPort: 8888
    nodePort: {{JUPYTER_NODEPORT}}
  type: NodePort 